on:
  pull_request:
    branches:
      - master
name: Pull request workflow
jobs: 
  validate_markets:
    name: Validate Markets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install --ignore-engines # will run `yarn install` command

      - name: Validate nodes schema
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: validate # validate using json schema