on:
  pull_request:
    branches:
      - testing
name: Pull request workflow
jobs: 
  validate_markets:
    name: Validate Featured Markets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install --ignore-engines # will run `yarn install` command

      - name: Validate featured markets schema
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: validate # validate using json schema
      
      - name: Test market entries for invalid/duplicate markets
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: check-configs mainnet testnet devnet # check using check_configs.ts script