on:
  pull_request:
    branches:
      - master
name: Pull request workflow
jobs: 
  validate_markets:
    name: Validate Config Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Set Node-js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.14.2'

      - name: Install Dependencies
        run: yarn install --ignore-engines # will run `yarn install` command

      - name: Validate config schema
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: config.schema.json
          INPUT_JSONS: configs/mainnet.json,configs/testnet.json,configs/devnet.json
      
      - name: Test configs for invalid/duplicate entries
        run: yarn check-configs mainnet testnet devnet # check using check_configs.ts script